version: '3.7'

services:
  redis:
    image: redis:5-alpine
    container_name: peepz-cache
    ports:
      - 6379:6379
    expose:
      - 6379

  api:
    image: gradle:5.6-jdk11
    container_name: peepz-java
    command: ["gradle", "build", "bootRun"]
    working_dir: /home/gradle/project
    volumes:
      - ./:/home/gradle/project
      - gradle_cache:/home/gradle/.gradle
    ports:
      - 8080:8080
    links:
      - redis
    environment:
      - REDIS_HOST=peepz-cache

volumes:
  gradle_cache: